name: Build/release

on: 
  push:
    tags:
      - v*


jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 14
          architecture: 'x64'

      - name: Install Dependency
        run: yarn install

      - name: Build/release Electron window app
        if: ${{ matrix.os == 'windows-latest' }}
        uses: samuelmeuli/action-electron-builder@v1
        with:
          build_script_name: electron:build:win
          use_vue_cli: true
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
      
      - name: Build/release Electron mac app
        if: ${{ matrix.os == 'macos-latest' }}
        uses: samuelmeuli/action-electron-builder@v1
        with:
          build_script_name: electron:build:mac
          use_vue_cli: true
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}